name: Build

on: push

env:
  CONAN_UPLOAD: https://api.bintray.com/conan/grisumbras/conan
  CONAN_LOGIN_USERNAME: grisumbras
  CONAN_USERNAME: grisumbras

jobs:
  build:
    strategy:
      matrix:
        version: [3.6.1]

    runs-on: ubuntu-latest

    steps:
      - name: Pull sources
        uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Enable uploads from master
        if: github.event.ref == 'refs/heads/master'
        run: echo "::set-env name=CONAN_PASSWORD::$CONAN_PASSWORD"
        env:
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

      - name: Run CPT
        uses: grisumbras/run-cpt@v0.2.0
        env:
          CONAN_STABLE_BRANCH_PATTERN: '---'
          CONAN_REFERENCE: sassc/${{ matrix.version }}@${{ env.CONAN_USERNAME }}/testing
          CONAN_GCC_VERSIONS: '7'
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release

  publish:
    needs: build

    if: github.event.ref == 'refs/heads/master'

    strategy:
      matrix:
        version: [3.6.1]

    runs-on: ubuntu-latest

    steps:
      - name: Pull sources
        uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Promote to stable
        uses: grisumbras/conan-promote@v0.3.0
        with:
          version: ${{ matrix.version }}
        env:
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
